[workspace]
resolver = "3"
members = ["crates/igloo", "crates/migration", "crates/blizzard", "crates/macros"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
async-trait = "0.1.89"
chrono = "0.4.42"
include_dir = "0.7.4"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
config = { version = "0.15.18", features = ["corn"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "json"] }
tracing-bunyan-formatter = "0.3.10"
migration = { path = "crates/migration" }
