[workspace]
resolver = "3"
members = ["crates/igloo", "crates/migration", "crates/blizzard", "crates/config", "crates/derive"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
async-trait = "0.1.89"
chrono = "0.4.42"
include_dir = "0.7.4"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "json"] }
migration = { path = "crates/migration" }
config = { path = "crates/config" }
miette = { version = "7.6.0", features = ["fancy"] }
knus = { version = "3.3.1", features = ["derive", "knus-derive"] }
sea-orm = { version = "2.0.0-rc", features = ["macros", "sqlx-postgres", "runtime-tokio"] }
