[package]
name = "config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
knus.workspace = true
figment = { version = "0.10.19", features = ["env"] }
tracing.workspace = true
miette.workspace = true
serde.workspace = true
config-proc-macro.path = "../config-proc-macro"