[package]
name = "igloo"
version = "0.1.0"
edition = "2024"

[dependencies]
which = "8.0.0"
inventory.workspace = true
async-trait.workspace = true
rayon = "1.11.0"
crossbeam = "0.8.4"
cuid2.workspace = true
thiserror.workspace = true
if_chain.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true