[package]
name = "cryo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
rustix = {workspace = true, features = ["runtime", "net", "process", "stdio", "event"]}
serde.workspace = true
postcard = { features = ["experimental-derive", "alloc"], version = "1.1.3" }