[package]
name = "macro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
macro-string = "0.1.4"
proc-macro2.workspace = true
quote.workspace = true
knus.workspace = true
syn.workspace = true